#! /bin/sh


###-- AutoStart --###
$HOME/.config/polybar/launch.sh
wal -i house.jpg
pgrep -x sxhkd > /dev/null || sxhkd &

###-- Bspc Options --###
bspc config border_width         0
bspc config window_gap          15
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc monitor eDP -d 1 2 3 4 5 6 7 8 9
bspc monitor DisplayPort-0 -d 10

###---set colors---###

bspc config focused_border_color "#4f9ea8" 
